# Generated by Django 5.2.16 on 2026-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('building', 'Academic Building'), ('library', 'Library'), ('lab', 'Laboratory'), ('cafeteria', 'Cafeteria'), ('student_affairs', 'Student Affairs'), ('parking', 'Parking'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('building_code', models.CharField(blank=True, help_text="e.g. 'Bldg A'", max_length=20)),
                ('x_position', models.DecimalField(decimal_places=2, help_text='Horizontal position, 0-100%', max_digits=5)),
                ('y_position', models.DecimalField(decimal_places=2, help_text='Vertical position, 0-100%', max_digits=5)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='campus_map__categor_d78e9d_idx')],
            },
        ),
    ]
