# Generated by Django 5.2.16 on 2026-07-08 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('assignment_created', 'created an assignment'), ('assignment_completed', 'completed an assignment'), ('resource_downloaded', 'downloaded a resource'), ('chat_message', 'chatted with the AI Assistant'), ('post_created', 'posted in the discussion board'), ('event_joined', 'joined an event'), ('profile_updated', 'updated their profile')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='bi-circle-fill', max_length=40)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx')],
            },
        ),
    ]
