# Generated by Django 5.2.16 on 2026-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lecturers/')),
                ('department', models.CharField(choices=[('computer_science', 'Computer Science'), ('mathematics', 'Mathematics'), ('business', 'Business Administration'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('english', 'English'), ('economics', 'Economics')], max_length=30)),
                ('subjects', models.CharField(help_text="Comma-separated list, e.g. 'Data Structures, Algorithms'", max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Mon/Wed 2:00–4:00 PM', max_length=200)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['department'], name='lecturers_l_departm_52295d_idx')],
            },
        ),
    ]
